#!/usr/bin/env python3

import asyncio
import logging

from optparse import OptionParser

from abuildd import __version__
from abuildd.repository import APKBuildRepository


logging.basicConfig(format='%(asctime)-15s: %(message)s')
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def banner(options, args):
    logger.info('abuildd-build version {v}'.format(v=__version__))
    logger.info('options: %r; args: %r', options, args)


def update(loop, repo):
    loop.run_until_complete(repo.update())


def build(loop, repo, targets, output):
    loop.run_until_complete(asyncio.gather(*[repo.build(target, output) for target in targets]))


def main():
    parser = OptionParser()
    parser.add_option('-g', '--git-repository', dest='git-repository', metavar='REPO',
                      help='clone APKBUILDs from REPO')
    parser.add_option('-d', '--destination', dest='destination', metavar='PATH',
                      help='path to deposit built packages in')
    parser.add_option('-p', '--parallel', action='store_true', dest='parallel', default=False,
                      help='build targets in parallel')
    options, args = parser.parse_args()

    banner(options, args)

    if not getattr(options, 'git-repository'):
        logger.error('--git-repository is required')
        return 1

    if not options.destination:
        logger.error('--destination is required')
        return 1

    loop = asyncio.get_event_loop()
    repo = APKBuildRepository.from_url(getattr(options, 'git-repository'))
    update(loop, repo)

    if not options.parallel:
        for target in args:
            build(loop, repo, [target], options.destination)
    else:
        build(loop, repo, args, options.destination)

    return 0


if __name__ == '__main__':
    exit(main())
